CREATE TABLE users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    nickname TEXT NOT NULL,
    avatar_url TEXT,
    chats JSONB DEFAULT '{}'::JSONB
);

CREATE TABLE chats (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    members JSONB DEFAULT '{}'::JSONB
);