class BaseAppException(Exception): ...

class UserExistError(BaseAppException): ...

class UserNotFoundError(BaseAppException): ...

class ChatNotFoundError(BaseAppException): ...

class WrongPasswordError(BaseAppException): ...

class InvalidTokenError(BaseAppException): ...

class InvalidMessagesError(BaseAppException): ...

class ExpiredTokenError(BaseAppException): ...

class NoPermissionError(BaseAppException): ...

class NoReadPermissionError(NoPermissionError): ...

class NoWritePermissionError(NoPermissionError):
    def __init__(self, message: dict):
        super().__init__()
        self.error_message = message